service: cqrs-test

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function

package:
  individually: true

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: false
    packager: 'yarn'
    excludeFiles: src/**/*.test.ts
  configFile: ${file(.env.${opt:stage, 'dev'}.yml):}

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  stage: ${self:custom.configFile.STAGE}
  region: ${self:custom.configFile.REGION}
  environment:
    STAGE: ${self:custom.configFile.STAGE}

functions:
  createOrder:
    handler: src/adapters/http/createOrder/createOrder.handler
    environment:
      ORDER_EVENT_STORE_TABLE: !Ref OrderEventStoreTable
    events:
      - http:
          path: orders
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:Query
        Resource: !GetAtt OrderEventStoreTable.Arn
  createProduct:
    handler: src/adapters/http/createProduct/createProduct.handler
    environment:
      PRODUCT_TABLE: !Ref ProductTable
    events:
      - http:
          path: products
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:PutItem
        Resource: !GetAtt ProductTable.Arn
  addProductToOrder:
    handler: src/adapters/http/addProductToOrder/addProductToOrder.handler
    environment:
      PRODUCT_TABLE: !Ref ProductTable
      ORDER_EVENT_STORE_TABLE: !Ref OrderEventStoreTable
    events:
      - http:
          path: orders/{id}/addProduct
          method: put
          request: 
            parameters: 
              paths: 
                id: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:Query
        Resource: !GetAtt OrderEventStoreTable.Arn
      - Effect: Allow
        Action: dynamodb:GetItem
        Resource: !GetAtt ProductTable.Arn
  onOrderEventStoreStream:
    handler: src/adapters/event/onOrderEventStoreStream/onOrderEventStoreStream.handler
    environment:
      QUEUE_URL: !Ref EventsQueue
    iamRoleStatements:
      - Effect: Allow
        Action: sqs:SendMessage
        Resource: !GetAtt EventsQueue.Arn
    events:
      - stream:
          type: dynamodb
          arn: !GetAtt OrderEventStoreTable.StreamArn
  eventsQueueWorker:
    handler: src/adapters/queue/eventsQueueWorker/eventsQueueWorker.handler
    environment:
      EVENT_BUS: !Ref EventBus
      ORDER_EVENT_STORE_TABLE: !Ref OrderEventStoreTable
    iamRoleStatements:
      - Effect: Allow
        Action: events:PutEvents
        Resource: !GetAtt EventBus.Arn
      - Effect: Allow
        Action: dynamodb:Query
        Resource: !GetAtt OrderEventStoreTable.Arn
    events:
      - sqs:
          arn: !GetAtt EventsQueue.Arn
  onOrderCreated:
    handler: src/adapters/event/onOrderCreated/onOrderCreated.handler
    environment:
      ORDER_TABLE: !Ref OrderTable
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
        Resource: !GetAtt OrderTable.Arn
    events:
      - eventBridge:
          eventBus: !Ref EventBus
          pattern:
            detail-type:
              - ORDER_CREATED
  onProductAddedToOrder:
    handler: src/adapters/event/onProductAddedToOrder/onProductAddedToOrder.handler
    environment:
      ORDER_TABLE: !Ref OrderTable
      PRODUCT_TABLE: !Ref ProductTable
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:UpdateItem
        Resource: !GetAtt OrderTable.Arn
      - Effect: Allow
        Action: dynamodb:GetItem
        Resource: !GetAtt ProductTable.Arn
    events:
      - eventBridge:
          eventBus: !Ref EventBus
          pattern:
            detail-type:
              - PRODUCT_ADDED_TO_ORDER
  getProduct:
    handler: src/adapters/http/getProduct/getProduct.handler
    environment:
      ORDER_TABLE: !Ref OrderTable
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:GetItem
        Resource: !GetAtt OrderTable.Arn
    events:
      - http:
          path: orders/{id}
          method: get
          request: 
            parameters: 
              paths: 
                id: true
  getProducts:
    handler: src/adapters/http/getProducts/getProducts.handler
    environment:
      ORDER_TABLE: !Ref OrderTable
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:Scan
        Resource: !GetAtt OrderTable.Arn
    events:
      - http:
          path: orders
          method: get



resources:
  - ${file(src/adapters/database/database.yml)}
  - ${file(src/adapters/event/eventBus.yml)}
  - ${file(src/adapters/queue/queue.yml)}